# Uncomment this line to define a global platform for your project
use_frameworks!
platform :ios, '8.0'

def demo_chat_frameworks
    #start - add Firebase
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Kingfisher'
    #end
    
    #start - add google adMob
    pod 'Google-Mobile-Ads-SDK'
    #end
    
    #start - Firebase analytics
    pod 'Firebase/Analytics'
    #end
    
    pod 'EZAlertController' #lib message
    
    #start - add Firebase crashlytics and login twitter
    pod 'Firebase/Crashlytics'
    pod 'TwitterKit'
    #end
    
    #Nifty cloud
    pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git'
    #end
    
    #start - tracking user in MAP
    pod 'GoogleMaps'
    pod 'Socket.IO-Client-Swift'
    #end
    
    #start - add pod support movie function
    pod 'Alamofire'
    pod 'youtube-ios-player-helper-swift'
    #end
    
    #start - add pod support music function
    pod 'RealmSwift', '~> 3.19.0', :modular_headers => true
    pod 'Realm', '~> 3.19.0', :modular_headers => true
    #end
    
    #start - add add support layout UI
    pod 'SnapKit'
    #end
end

target 'HuCaChat_Dev' do
    demo_chat_frameworks
end

target 'HuCaChat_Release' do
    demo_chat_frameworks
end
